services:

  postgres:
    image: postgres:15
    container_name: postgres_users
    restart: always
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: interface_industrial_api
    restart: always
    ports:
      - "5071:5071"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5071
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=usersdb;Username=postgres;Password=postgres"
      Jwt__Key: "N9y1B8TkJDayGmLrBKBDlCYLl4lHzdnk"
      Jwt__Issuer: "UserCrudApi"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge